# Config file for Telegram Captcha Bot

# Button text
button_text = "I am not a spammer!"

# Bot sends this message to new users
welcome_message = "This is spam protection. You have 30 seconds to press the button or you will be banned!"

# Edit welcome message with this text if user passed validation
after_success_message = "Welcome! Access granted."

# Edit welcome message with this text if user failed validation
after_fail_message = "User didn't pass the validation and was banned."

# Show success and failure messages or delete them. Pick "show" or "del"
print_success_and_fail_messages_strategy = "del"
